import { Octokit } from "@octokit/rest";
import type { TemplateFile, GitHubRepoResult, GeneratorOptions } from "./types";

export async function publishToGitHub(
  options: GeneratorOptions,
  files: TemplateFile[],
): Promise<GitHubRepoResult> {
  const octokit = new Octokit({ auth: options.githubToken });

  const user = await octokit.users.getAuthenticated();
  const owner = user.data.login;

  const repo = await octokit.repos.createForAuthenticatedUser({
    name: options.repoName,
    description: `A ${options.framework} SaaS boilerplate generated by SaaSForge`,
    private: false,
    auto_init: false,
  });

  const repoUrl = repo.data.html_url;
  const cloneUrl = repo.data.clone_url;

  const existingRef = await octokit.git.getRef({
    owner,
    repo: options.repoName,
    ref: "heads/main",
  }).catch(() => null);

  if (!existingRef) {
    const latestCommit = await octokit.git.createCommit({
      owner,
      repo: options.repoName,
      message: "Initial commit",
      tree: await createTree(octokit, owner, options.repoName, files),
      parents: [],
    });

    await octokit.git.createRef({
      owner,
      repo: options.repoName,
      ref: "refs/heads/main",
      sha: latestCommit.data.sha,
    });
  } else {
    const latestCommit = await octokit.git.createCommit({
      owner,
      repo: options.repoName,
      message: "Add generated boilerplate",
      tree: await createTree(octokit, owner, options.repoName, files),
      parents: [existingRef.data.object.sha],
    });

    await octokit.git.updateRef({
      owner,
      repo: options.repoName,
      ref: "heads/main",
      sha: latestCommit.data.sha,
    });
  }

  return { repoUrl, cloneUrl, name: options.repoName };
}

async function createTree(
  octokit: Octokit,
  owner: string,
  repo: string,
  files: TemplateFile[],
) {
  const blobs = await Promise.all(
    files.map(async (file) => {
      const blob = await octokit.git.createBlob({
        owner,
        repo,
        content: file.content,
        encoding: "utf-8",
      });
      return {
        path: file.path,
        mode: "100644" as const,
        type: "blob" as const,
        sha: blob.data.sha,
      };
    }),
  );

  const tree = await octokit.git.createTree({
    owner,
    repo,
    tree: blobs,
  });

  return tree.data.sha;
}
